### ISSUE TITLE
WithExpand not working

### ISSUE THREAD

**Issue by MichaelTrefz** [commercetools/commercetools-sdk-php-v2#100]
**Describe the bug**
If i get a order and want it to expand, no error is showing and no expansion is coming uo

**To Reproduce**
$commercetoolsOrder = $this->apiRoot
                    ->orders()
                    ->get()
                    ->withExpand('PaymentInfo')
                    ->execute();

**Expected behavior**
FROM normal tax it should be expand within tax to obj. My example in Screenshot ist with PaymentInfo. But you can do it with Customers too
  {
    "id": "<example-product-id>",
    "version": 4,
    "productType": {
      "typeId": "product-type",
      "id": "<example-product-type-id>"
    },
    ...
    "taxCategory": {
      "typeId": "tax-category",
      "id": "<example-tax-category-id>"
    },
    ...
  }
{
  "id": "<example-product-id>",
  "version": 4,
  "productType": {
    "typeId": "product-type",
    "id": "<example-product-type-id>"
    "obj": {
        "id": "<example-product-type-id>",
        "version": 4,
        "name": "Example Product Type",
        "description": "example Product Type to showcase Reference Expansion",
        "classifier": "Complex",
        "attributes": [
        ....
      ],
  },
  ...
  "taxCategory": {
    "typeId": "tax-category",
    "id": "<tax-category-id>"
    "obj": {
        "id": "<tax-category-id>",
        "version": 2,
        "name": "Standard tax category",
        "rates": [
          {
            "name": "5% US",
            "amount": 0.05,
            "includedInPrice": false,
            "country": "US",
            "id": "zJJ5KIGH"
          },
          {
            "name": "19% MwSt",
            "amount": 0.19,
            "includedInPrice": true,
            "country": "DE",
            "id": "893f_nXJ"
          }
        ],
  ...
}
**Screenshots/Code snippet**
<img width="622" alt="image" src="https://user-images.githubusercontent.com/33512869/203634872-7bd07551-c6f4-4cf6-9765-f3fe2ea1a428.png">

**Stack information (please complete the following information):**
 - PHP: 7.4
-  commercetools/php-sdk : 2.16

**Additional context**

**Comment by jenschude** [comment]
For reference expansion you have to provide the a JSON path similar expression. Please see here: https://docs.commercetools.com/api/general-concepts#expansion-paths

So in your example it would be:

```
$commercetoolsOrder = $this->apiRoot
  ->orders()
  ->get()
  ->withExpand('paymentInfo.payments[*]')
  ->execute();
```

The section about reference expansion also states why it's not failing:

> Expansion of references does not cause requests to fail even if not all of the references can be expanded (for example, because the referenced resource cannot be found). The server will try to expand as much as possible but never beyond what the client requested. It is up to the client to decide which referenced resources it deems critical for completing a specific use-case, for example, by either treating it as an error or by just not rendering/returning the missing information.

See https://docs.commercetools.com/api/general-concepts#reference-expansion

**Comment by MichaelTrefz** [comment]
Thanks for this quick reply. Its working.
But how do you know explizit paymentInfo.payments[*]
I have the exact same problem with expansion from customers. How do you knwo the exact path?
I didn´t found it in the docu

**Comment by jenschude** [comment]
It's abou the path to the field in the JSON structure and the field has to be of a reference type. The `customerId` in the order is not of type reference and therefor can't be expanded. The reason for this is that the customer itself is only losely coupled to the order.

**Comment by MichaelTrefz** [comment]
Thanks jens for your explanations
