### ISSUE TITLE
MyCartDraftModel do not support for set shippingMode

### ISSUE THREAD

**Issue by lchhieu** [commercetools/commercetools-sdk-php-v2#117]
**It seems MyCartDraftModel do not support for set shippingMode**
I want to set shippingMode to Multiple but cannot do that when using MyCartDraftModel

**Comment by jenschude** [comment]
The Me-Endpoints are limited in the actions they support. To set the shippingmode you either have to use the normal cart endpoint or to use an extension to update the shipping method from your backend

**Comment by jenschude** [comment]
As the SDKs only support the documented fields I forward this to the respective teams. Once it has been added to the docs it will come to the SDK too.

**Comment by jenschude** [comment]
We released 10.2.0 which adds the shippingMode field to the MyCartDraft
