### ISSUE TITLE
`405 Method Not Allowed` response from the base example with us-central1 zone

### ISSUE THREAD

**Issue by MurzNN** [commercetools/commercetools-sdk-php-v2#175]
**Describe the bug**
I can't make work the base example from the readme with the `us-central1` zone, I'm receiving a `405 Method Not Allowed` error.

**To Reproduce**
1. Copy-paste the example from the readme.
2. Set the $authUri to 'https://auth.us-central1.gcp.commercetools.com'.
3. Execute the code.

Result:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://auth.us-central1.gcp.commercetools.com` resulted in a `405 Method Not Allowed` response in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

**Expected behavior**
The correct response from the API, or at least - `401 Unauthorized` response.

**Screenshots/Code snippet**
```php
use Commercetools\Api\Client\ApiRequestBuilder;
use Commercetools\Api\Client\ClientCredentialsConfig;
use Commercetools\Api\Client\Config;
use Commercetools\Client\ClientCredentials;
use Commercetools\Client\ClientFactory;
use GuzzleHttp\ClientInterface;

require_once __DIR__ . '/vendor/autoload.php';

const CLIENT_ID = 'my_client_id';
const CLIENT_SECRET = 'my_client_secret';
const PROJECT_KEY = 'my_project_key';
const OAUTH_URL = 'https://auth.us-central1.gcp.commercetools.com/oauth/token';
const API_URL = 'https://api.us-central1.gcp.commercetools.com';

$authConfig = new ClientCredentialsConfig(new ClientCredentials(CLIENT_ID, CLIENT_SECRET), [], OAUTH_URL);

$client = ClientFactory::of()->createGuzzleClient(
  new Config([], API_URL),
  $authConfig
);

$builder = new ApiRequestBuilder($client);
$request = $builder->withProjectKey(PROJECT_KEY)->get();
$response = $request->execute();
```

**Stack information (please complete the following information):**
 - PHP: 8.1
 - SDK: 10.3.0

**Comment by MurzNN** [comment]
My issue is resolved by adding the path to the `$authUri` like this:
```php
$authConfig = new ClientCredentialsConfig(new ClientCredentials(CLIENT_ID, CLIENT_SECRET), [], 'https://auth.us-central1.gcp.commercetools.com/oauth/token');
```
instead of:
```
$authConfig = new ClientCredentialsConfig(new ClientCredentials(CLIENT_ID, CLIENT_SECRET), [], 'https://auth.us-central1.gcp.commercetools.com);
```
Is this a correct way to configure a custom auth endpoint?

**Comment by jenschude** [comment]
Yes. The auth URI has to include the full URI.

Also please be aware that there are two ApiRequestBuilder classes.

```
Commercetools\Api\Client\ApiRequestBuilder
Commercetools\Client\ApiRequestBuilder
```

The first one is auto generated and not bound to a specific project. The second one is manually written, bound to a specific project and also includes the methods to the different endpoints. We should update the readme to avoid some of the confusion.

**Comment by MurzNN** [comment]
Thank you for the information, will be good to document this, because it is not obvious. I spend a lot of time trying to understand why it is not working while migrating from 1.x to 2.x, cuz in 1.x the host is enough, without path.

I made a PR https://github.com/commercetools/commercetools-sdk-php-v2/pull/176 to improve the readme with this, please take a look. 

Maybe it'll also be good to update the migration documentation too?

**Comment by MurzNN** [comment]
> Also please be aware that there are two ApiRequestBuilder classes.
> 
> ```
> Commercetools\Api\Client\ApiRequestBuilder
> Commercetools\Client\ApiRequestBuilder
> ```

@jenschude Maybe rename the second class to just `RequestBuilder` or something else? Having two very similar classes with the same name creates a lot of confusion for newbies like me! :)

**Comment by jenschude** [comment]
Not as simple anymore without breaking changes. :)
