### ISSUE TITLE
Add method to clear cache or force refresh the access token

### ISSUE THREAD

**Issue by MurzNN** [commercetools/commercetools-sdk-php-v2#180]
**Is your feature request related to a problem? Please describe.**
The access token by default gets cached for 172800 seconds.
But for debugging and unit testing purposes, I need to clear the cached token to force refreshing the token.

**Describe the solution you'd like**
Will be good to have something like this:
```php
$builder = new ApiRequestBuilder($client);
$result1 = $builder->withProjectKey(PROJECT_KEY)->get()->execute();
$builder->clearCache(); // or something like $builder->getCache->clear();
// or $builder->refreshToken();
$result2 = $builder->withProjectKey(PROJECT_KEY)->get()->execute();
```

**Describe alternatives you've considered**
If a way to clear cache or force refresh the access token already exists, could you please describe it? Thanks!

**Comment by jenschude** [comment]
You can use any PSR-6 or PSR-16 compatible cache

```

ClientFactory->createGuzzleClientForHandler(
	$config,
	OAuthHandlerFactory::ofAuthConfig($authConfig, $cache)
)
```

**Comment by MurzNN** [comment]
Yeah, that way works well, thank you! I just could not find how to pass a custom cache to the auth.
