### ISSUE TITLE
OrderEditModel::getResult return only generic OrderEditResultModel class

### ISSUE THREAD

**Issue by AlesZurek** [commercetools/commercetools-sdk-php-v2#226]
**Describe the bug**
`\Commercetools\Api\Models\OrderEdit\OrderEditModel::getResult`

    /**
     * <p>For applied edits, it's a summary of the changes on the Order.
     * For unapplied edits, it's a preview of the changes.</p>
     *
     *
     * @return null|OrderEditResult
     */
    public function getResult()
    {
        if (is_null($this->result)) {
            /** @psalm-var stdClass|array<string, mixed>|null $data */
            $data = $this->raw(self::FIELD_RESULT);
            if (is_null($data)) {
                return null;
            }

            $this->result = OrderEditResultModel::of($data);
        }

        return $this->result;
    }

Method `\Commercetools\Api\Models\OrderEdit\OrderEditResultModel::resolveDiscriminatorClass`
is not being used here so it returns generic Model but not the specific model of the OrderEditResult (child class)

Example of the code from CartDiscountTarget
`\Commercetools\Api\Models\Cart\DirectDiscountDraftModel::getTarget`

    /**
     * <p>Defines what segment of the Cart will be discounted.</p>
     * <p>If <code>value</code> is set to <code>giftLineItem</code>, this must not be set.</p>
     *
     *
     * @return null|CartDiscountTarget
     */
    public function getTarget()
    {
        if (is_null($this->target)) {
            /** @psalm-var stdClass|array<string, mixed>|null $data */
            $data = $this->raw(self::FIELD_TARGET);
            if (is_null($data)) {
                return null;
            }
            $className = CartDiscountTargetModel::resolveDiscriminatorClass($data);
            $this->target = $className::of($data);
        }
    
        return $this->target;
    }

It looks like that the one line
`$className = OrderEditResultModel::resolveDiscriminatorClass($data);`
is missing there in the `\Commercetools\Api\Models\OrderEdit\OrderEditModel::getResult`

**To Reproduce**
1. Create order
2. Create order edit
3. Get order edit result object

Example code
```
$orderEdit = $this->commercetoolsClient
            ->orders()
            ->edits()
            ->post(/*...*/)
            ->execute();

$orderEditResult = $orderEdit->getResult(); // $orderEditResult is instance of OrderEditResultModel
```

**Expected behavior**
Method `\Commercetools\Api\Models\OrderEdit\OrderEdit::getResult` should return one of the models depending on the type
- `OrderEditAppliedModel`
- `OrderEditNotProcessedModel`
- `OrderEditPreviewFailureModel`
- etc.

and not the generic `OrderEditResultModel`.

**Screenshots/Code snippet**
If applicable, add screenshots or code samples to help explain your problem.

**Stack information (please complete the following information):**
 - PHP: 8.2
 - SDK: 10.5.0

**Additional context**

**Comment by jenschude** [comment]
Thanks for the report.

We just released 10.6.0 with a fix to the issue. Turned out that also other classes were affected as can be seen here https://github.com/commercetools/commercetools-sdk-php-v2/pull/229
