### ISSUE TITLE
PHP SDK ME Endpoint support

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-sdk-php-v2#59]
Implement the functionalities of the me endpoint in the PHP SDK

Acceptance Criteria
- [ ] Study how its done in .NET SDK.
- [ ] Implement ME endpoint in PHP SDK v2.
- [ ] Implement demo by reusing as much as possible from the .NET demo app.
- [ ] keep the demo app consistent in UX

**Scope of implementation**
- [ ] ME endpoints can be used server-side 
- [ ] Re-authentication using refresh tokens 
- [ ] Anonymous checkout possible 
- [ ] Switching from anonymous to password flow 
- [ ] Simplify overall authentication process

**Comment by anjaliVashisth** [comment]
Migrated to Jira https://commercetools.atlassian.net/browse/DEVX-288
