### ISSUE TITLE
Upgrade psr/cache to v3 to make SDK compatible with newer Symfony versions 

### ISSUE THREAD

**Issue by mschindler83** [commercetools/commercetools-sdk-php-v2#72]
**Is your feature request related to a problem? Please describe.**

Currently I am unable to install the SDK with Symfony 6.0.*.
Dependency clash with this SDK and symfony/cache

CT-SDK: psr/cache ^v1
symfony/cache: psr/cache ^v2.0|^v3.0

**Describe the solution you'd like**

Up to date dependencies

**Comment by jenschude** [comment]
Updated the dependencies in #73

Thanks for the report!

**Comment by jenschude** [comment]
Released a new version 4.4.0 with the update

**Comment by mschindler83** [comment]
Thanks a lot !
