### ISSUE TITLE
setCustom is missing in CustomerAddressBuilder inside importer 

### ISSUE THREAD

**Issue by fsalmabbg** [commercetools/commercetools-sdk-php-v2#92]
I am working on migrating customer data from our current shop to commercetool. I am using importer to migrate the data, but I am not able to use it to migrate customer custom address fields using importer directly without using the API.
 
Using importer to migrate these fileds will save sending requests using API for each customer to migrate only custom address

**Comment by barbara79** [comment]
already in this release https://github.com/commercetools/commercetools-sdk-php-v2/releases/tag/7.0.0
