### ISSUE TITLE
Support current versions of psr/log

### ISSUE THREAD

**Issue by grubersjoe** [commercetools/commercetools-sdk-php-v2#95]
Hey. This project depends on `psr/log:^1.0`. In our Symfony based project we're currently using `psr/log:^2.0` and consequently we get version conflicts when trying to install this package with Composer. 

We could downgrade to `psr/log:^1.0` but this is not our preferred option. Would it be possible to change the version requirements of this library to the following like it already has been done for `psr/cache` etc?

```json
"psr/log": "^1.0 || ^2.0 || ^3.0",
```

The different versions only aim at different PHP versions so this should not be an issue.

Thank you!

**Comment by jenschude** [comment]
Just released 7.1.0 which widens the psr/log constraint.

Thanks for the report
