### ISSUE TITLE
Not able to set empty values for category description

### ISSUE THREAD

**Issue by DavidePastore** [commercetools/commercetools-sdk-php-v2#99]
**Describe the bug**
Í'm trying to overwrite the localized description field of a category, using empty values but this is not working.

**To Reproduce**
- create a category;
- set the category description for a particular locale (e.g. en-GB);
- try to overwrite the category description with an empty value using the SDK.

**Expected behavior**
The operation should overwrite correctly the description.

**Screenshots/Code snippet**
```php
$version = 12;
$categoryCode = 'my-category';
$actionsCollection = CategoryUpdateActionCollection::of();
$action = CategorySetDescriptionActionBuilder::of()
            ->withDescription(LocalizedStringBuilder::fromArray([])->build())
            ->build();
$actionsCollection->add($action);
$categoryUpdate = CategoryUpdateBuilder::of()
            ->withVersion($version)
            ->withActions($actionsCollection)
            ->build();

// Correctly configure the $api object...
$api->categories()
            ->withKey($categoryCode)
            ->post($categoryUpdate)
            ->withExpand(['parent'])
            ->execute();
```

This code will generate the given request body:

```json
{
	"version": 12,
	"actions": [
		{
			"action": "setDescription",
			"description": []
		}
	]
}
```

The response that it will get is:

```json
{
	"statusCode": 400,
	"message": "Request body does not contain valid JSON.",
	"errors": [
		{
			"code": "InvalidJsonInput",
			"message": "Request body does not contain valid JSON.",
			"detailedErrorMessage": "actions -> description: JSON object expected."
		}
	]
}
```

If I change the request body to:

```json
{
	"version": 12,
	"actions": [
		{
			"action": "setDescription",
			"description": {}
		}
	]
}
```

the response will be ok.

**Stack information (please complete the following information):**
 - PHP: 8.1
 - SDK: 6.0.1

**Additional context**
Note that I've found the same issue for other fields as well: meta description and meta title (they are both localizable).

**Comment by jenschude** [comment]
To unset you have to not set the description at all

```
$action = CategorySetDescriptionActionBuilder::of()
            ->build();
```

**Comment by DavidePastore** [comment]
Thank you @jenschude. In the end, I used the `null` value when the array is empty to make it cleaner.

**Comment by jenschude** [comment]
Btw this works also for other actions as upon serialization fields with a null value will be omitted.
